# Generated by Django 5.0.6 on 2024-06-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bartsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_categoryimage', models.ImageField(blank=True, null=True, upload_to='category images')),
            ],
        ),
    ]
