# Generated by Django 5.0.6 on 2024-07-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bartsapp', '0002_sub_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Work_year', models.IntegerField(blank=True, null=True)),
                ('Started_date', models.IntegerField(blank=True, null=True)),
                ('Finished_date', models.IntegerField(blank=True, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='category images')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='category images')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='category images')),
                ('Image5', models.ImageField(blank=True, null=True, upload_to='category images')),
            ],
        ),
    ]
