# Generated by Django 5.0.6 on 2024-07-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bartsapp', '0003_projectdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdb',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to='category images'),
        ),
    ]
