# Generated by Django 5.0.6 on 2024-07-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bartsapp', '0005_alter_projectdb_finished_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_categorydb',
            name='Terms_conditions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
